### ISSUE TITLE
Bitbucket 7.2.x compatibility

### ISSUE THREAD

**Issue by holgerstolzenberg** [Cyanoth/Bitbucket-EagerPR-Updates#2]
We have been hit by this problem after upgrading from Bitbucket Server 6 to 7.2.5.
Now our Concourse PR builds fail in the pipes as the bitbucket pull request resource (https://github.com/mmb/concourse-bitbucket-pullrequest-resource) also relies onto the internal refs.

As a workaround I tried to use this plugin, but I did not manage to get it working.

Can you please confirm the plugin is compatible with Bitbucket 7.2(.5) or provide a release that is?

**Comment by Cyanoth** [comment]
Our production instance is Bitbucket 7.2.1 and we've been using this plugin as a workaround for a couple of months without issue. I've looked at the changelog between 7.2.1 & 7.2.5, there are no obvious changes which would affect the functionality of this plugin, but of course I have not tried it on 7.2.5 - it should still work.

Important to note, as mentioned in the README & Atlassian's jira ticket: BSERV-12284. This plugin updates the `refs/pull-requests/*/from` internal ref immediately on certain pull-request events; Otherwise you need to query an API / browse it in the UI for that ref to refreshed.

This plugin does not bring back the internal ref: `refs/pull-requests/*/merge`, which does not exist in Bitbucket 7+ due to the switch to a two-way diff.

Perhaps you could expand on 'not manage to get it working'?

**Comment by holgerstolzenberg** [comment]
Okay thanks for the clarification. I missed the interesting part:

> This plugin does not bring back the internal ref: refs/pull-requests/*/merge, which does not exist in Bitbucket 7+ due to the switch to a two-way diff.

For us that means will still have to update the affected Concourse Ressource if when using the plugin, which is kinda around the corner. It looks like we have to go the API path with the resource.

Thanks for the quick answer.
